### ISSUE TITLE
Suggestion on how to use `\only` or `\onslide` for annotated equations

### ISSUE THREAD

**Issue by zaccharieramzi** [synercys/annotated_latex_equations#4]
Thank you so much for these examples that I find really clear, and beautifully designed.

I was wondering if you had any suggestions on how to make each annotation appear one-by-one in Beamer, using for example the `\only` or `\onslide` commands.
Of course one way is to copy-paste the equation in different `\only` blocks, but I was wondering if you had thought of something more robust.

EDIT
----
I just want to clarify that for the `tikzfigure` it's relatively obvious how to do it, it's more for the highlight part that I am not sure how to proceed efficiently.

**Comment by sibin** [comment]
I haven't explored this option, sorry. Hopefully someone else will have an idea on how to do it.
